### ISSUE TITLE
Create "create class" page.

### ISSUE THREAD

**Issue by morgaalb** [OSU-CS290-F16/final-project-cgrb-actf#3]

**Comment by millelog** [comment]
All the work with the views and express-handlebars looks great! I've set up nginx to no longer serve any of the files statically but instead pass everything from root to be rendered by node. you can see your current iteration of the create class page up at https://jupyter.cgrb.oregonstate.edu/classes/create for debugging

**Comment by millelog** [comment]
Also just added a ~~'details'~~ 'description' textfield to our database so it can handle that field now too (hopefully)

**Comment by millelog** [comment]
Updated help command for class creation script:

[root@jupyter docker_python]# ./manage_class.py create_class -h
usage: manage_class.py create_class [-h] -c CLASS_NAME -r READABLE_NAME -d
                                    DESCRIPTION -f FIRST -l LAST -e EMAIL -u
                                    USER -n HOSTNAME -v VERSION -m MEM_LIMIT
                                    -s CPU_SHARE

optional arguments:
  -h, --help            show this help message and exit
  -c CLASS_NAME, --class_name CLASS_NAME
                        The name of the class as defined by the class
                        directory in /ACTF
  -r READABLE_NAME, --readable_name READABLE_NAME
                        The full, human readable name for the class. Please
                        encapsulate with quotes if there are spaces.
  -d DESCRIPTION, --description DESCRIPTION
                        A brief description of the class. Must be encapsulated
                        with quotes.
  -f FIRST, --first FIRST
                        The instructor's first name.
  -l LAST, --last LAST  The instructor's last name.
  -e EMAIL, --email EMAIL
                        The instructor's email.
  -u USER, --user USER  The instructor's username.
  -n HOSTNAME, --hostname HOSTNAME
                        The local hostname of the machine that will run this
                        container.
  -v VERSION, --version VERSION
                        The version of the jupyterhub/actf docker image to
                        use.
  -m MEM_LIMIT, --mem_limit MEM_LIMIT
                        Memory limit for the container. Format:
                        [number][unit], unit = k, m or g.
  -s CPU_SHARE, --cpu_share CPU_SHARE
                        Number of weighted CPU shares to alot this class,
                        default is 1024 for even cpu division accross all
                        containers

**Comment by morgaalb** [comment]
Oh hey, there is a description option now! I missed this post when I sent out my email earlier. I'm still getting used to the Git issues workflow and didn't think to check the comments here.
