### ISSUE TITLE
404 is being handled by Nginx

### ISSUE THREAD

**Issue by millelog** [OSU-CS290-F16/final-project-cgrb-actf#6]
I'm not quite sure how to make sure node handles our 404 instead of nginx, maybe I'll just route nginx to a static 404 page that looks the same

**Comment by millelog** [comment]
Oh just kidding the static 404 in the repository is the nginx one. If someone could update that to use the templates and maintain a common theme that'd be good.

**Comment by morgaalb** [comment]
Cool. I'll do the 404 thing when I get a chance. Shouldn't be hard.
