### ISSUE TITLE
Verify that class creation page works correctly.

### ISSUE THREAD

**Issue by morgaalb** [OSU-CS290-F16/final-project-cgrb-actf#8]
Verify that the new class creation page works correctly.

- [x] The page should call the python script correctly and actually insert the class into the DB

- [ ] The results given to the user after class creation should make sense and be correct.

**Comment by millelog** [comment]
So after a TON of wrangling around in the python and a complete wipe of the database the class creation works from a backend perspective. When you put in the info and click create class that class will be there when you refresh the page.

The post itself doesn't seem to resolve properly though and gives a syntax error in the class_server I think which messes with the completion method. 

The Class page template still needs a field for the description as well but everything now works with the description field in the backend. Just need to call it from handlebars.

**Comment by millelog** [comment]
Maybe kirk could work on updating the class page template and making a nice redirect for when the class is created successfully? That stdout to the webpage was really cool for debugging though. Awesome work Al!

**Comment by Kirksten3** [comment]
@millelog What doesn't seem to be working on the class page template? It appears that the description field is there and being passed on to the server just fine. I can do a redirect back to index or something if that is needed after. It looks like this issue was just that it was returning JSON back instead of rendering a page upon completion. I can have it log the JSON result too or something.

**Comment by millelog** [comment]
Oh I jmeant that the page for the newly created class doesn't have the
description on it. I see the descriptions in the database just fine though.
And well Al made a thing that pops up on successful creation but it doesn't
seem to be fully functional. I'm not sure why

**Comment by Kirksten3** [comment]
Well I'm setting it up right now so that it will render the newly created page on page create and console log the result of the child_process exec. I'll make a new PR in a bit. Is there anything else that needs to be added? Also is the :thisClass param for the classes/:thisClass/ page the class code?

**Comment by morgaalb** [comment]
Logan, could you be more specific about what's not working with the doodad that pops up? Does it not give the output of the python script? Also, where is this syntax error? Can you give some repro steps?

**Comment by Kirksten3** [comment]
Is this what you had in mind logan? https://github.com/OSU-CS290-F16/final-project-cgrb-actf/pull/9

There's the PR for the updates that were mentioned.

**Comment by millelog** [comment]
I get two things when I click add class:

1.
Failed to load resource: the server responded with a status of 502 (Bad Gateway) http://jupyter.cgrb.oregonstate.edu/classes/create/add

2.
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (http://jupyter.cgrb.oregonstate.edu/index.js:116:15)

It was outputting the python script when it wasn't completing but now that it is completing nothing seems to be outputted.

**Comment by millelog** [comment]
I know what's going on....

**Comment by Kirksten3** [comment]
Any reason why the create page isn't wrapped in a form tag? Is there JS to handle the post?

**Comment by morgaalb** [comment]
There is JS to handle the post. We could wrap it up in a form tag if we wanted to, but I just had momentum with the AJAX thing so I did that instead.
